services:
  catalog-service:
    build: ./catalog-service
    depends_on:
      - mongo-catalog
    ports:
      - "3001:3001"
  mongo-catalog:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-catalog-data:/data/db

volumes:
  mongo-catalog-data:
