services:
  frontend:
    build: ./frontend-service
    ports:
      - "5500:80"
  api-gateway:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - catalog-service
      - order-service
      - rating-service
      - notification-service
  catalog-service:
    build: ./catalog-service
    depends_on:
      - mongo-catalog
    ports:
      - "3001:3001"
  order-service:
    build: ./order-service
    depends_on:
      - mongo-order
      - rabbitmq-service
    ports:
      - "3002:3002"

  rating-service:
    build: ./rating-service
    depends_on:
      - mongo-rating
      - rabbitmq-service
    ports:
      - "3003:3003"
  notification-service:
    build: ./notification-service
    depends_on:
      - mongo-notification
      - rabbitmq-service
    ports:
      - "3004:3004"
  mongo-catalog:
    image: mongo:8
    volumes:
      - mongo-catalog-data:/data/db
  mongo-order:
    image: mongo:8
    volumes:
      - mongo-order-data:/data/db
  mongo-rating:
    image: mongo:8
    volumes:
      - mongo-rating-data:/data/db
  mongo-notification:
    image: mongo:8
    volumes:
      - mongo-notification-data:/data/db
  rabbitmq-service:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  mongo-catalog-data:
  mongo-order-data:
  mongo-rating-data:
  mongo-notification-data:
