const seedCakes = [
  {
    name: "Chocolate Truffle Cake",
    description: "Rich chocolate cake with a smooth truffle frosting.",
    category: "Birthday",
    price: 900,
    available: true,
    imageReference: "chocolate-truffle.jpg",
  },
  {
    name: "Red Velvet Cake",
    description: "Soft red velvet cake layered with creamy cheese frosting.",
    category: "Birthday",
    price: 850,
    available: true,
    imageReference: "red-velvet.jpg",
  },
  {
    name: "Black Forest Cake",
    description: "Classic chocolate cake with cherries and whipped cream.",
    category: "Classic",
    price: 750,
    available: true,
    imageReference: "black-forest.jpg",
  },
  {
    name: "Vanilla Celebration Cake",
    description: "Light vanilla sponge cake with vanilla buttercream.",
    category: "Birthday",
    price: 650,
    available: true,
    imageReference: "vanilla-celebration.jpg",
  },
  {
    name: "Belgian Chocolate Cake",
    description: "Premium chocolate cake made with Belgian chocolate.",
    category: "Premium",
    price: 1400,
    available: true,
    imageReference: "belgian-chocolate.jpg",
  },
  {
    name: "Butterscotch Cake",
    description: "Vanilla sponge with butterscotch cream and crunchy caramel.",
    category: "Classic",
    price: 800,
    available: true,
    imageReference: "butterscotch.jpg",
  },
  {
    name: "Strawberry Cream Cake",
    description: "Fresh strawberry cake layered with whipped cream.",
    category: "Anniversary",
    price: 1000,
    available: true,
    imageReference: "strawberry-cream.jpg",
  },
  {
    name: "Wedding Fruit Cake",
    description:
      "Elegant fruit cake prepared specially for wedding celebrations.",
    category: "Wedding",
    price: 2200,
    available: true,
    imageReference: "wedding-fruit.jpg",
  },
  {
    name: "Coffee Mocha Cake",
    description: "Coffee-infused chocolate cake with mocha frosting.",
    category: "Premium",
    price: 1200,
    available: false,
    imageReference: "coffee-mocha.jpg",
  },
  {
    name: "Pineapple Cake",
    description: "Soft vanilla sponge with pineapple pieces and cream.",
    category: "Classic",
    price: 700,
    available: true,
    imageReference: "pineapple.jpg",
  },
];

module.exports = seedCakes;
